version: '3.5'

services:
  frontend:
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src

  api:
    command: npm run start
    volumes:
      - ./server/src:/usr/src/app/src
